"""Words on the solar DC home illustration, by language: en (English), hi (Hindi), or (Odia).
Used by build_dc_home.py. Keys are the same in every language; HTML entities are allowed."""

TEXT = {
    "en": {
        "title": "Solar DC Home",
        "south": "SOUTH", "north": "NORTH", "east_entrance": "EAST · ENTRANCE",
        "N": "N", "S": "S", "E": "E", "W": "W",
        "sun": "Sun in the southern sky",
        "panels_face": "Panels face south to catch the sun all day",
        "north_balcony": "NORTH BALCONY", "tank": "tank",
        "panels_tilted": "SOLAR PANELS TILTED TO FACE SOUTH",
        "bedroom": "BEDROOM", "family_room": "FAMILY ROOM", "staircase": "STAIRCASE",
        "living_room": "LIVING ROOM", "kitchen": "KITCHEN", "dc_utility": "DC UTILITY",
        "riser_1": "DC riser from", "riser_2": "the board below",
        "charge_controller": "charge controller", "battery": "BATTERY", "with_bms": "with BMS",
        "dc_board": "DC BOARD", "distribution": "48 V distribution",
        "boundary_gate": "BOUNDARY LIGHT &amp; GATE MOTOR",
        "legend": [
            ("Solar panels facing south", "Tilted rows on the terrace catch the sun from morning to evening."),
            ("Stair room &amp; water tank", "The terrace stays usable; panels sit clear of the tank's shadow."),
            ("Entrance on the east", "Morning light at the door; porch with DC light and steps."),
            ("Boundary wall lights", "DC lamps on every pillar light the compound at night."),
            ("Sliding gate", "Slides along the inside of the boundary wall on a rail."),
            ("DC gate motor", "Opens and closes the gate on battery power, even in a power cut."),
            ("Porch light", "Driverless DC LED at the main door."),
            ("DC cable route", "Red (+) and black (−) cables run from the panels to the DC utility room."),
            ("North balcony", "First-floor balcony on the north side, wrapping the north-east corner. Soft, glare-free north light and its own DC wall light."),
        ],
        "inside": ["Rooftop solar", "MPPT charge controller", "Battery + BMS", "48 V DC board", "Driverless LED lights",
                   "BLDC fans &amp; exhaust", "Touch panels", "Mechanical switches", "DC &amp; USB-C sockets", "DC fridge",
                   "Gate motor", "Boundary lights"],
        "wiring": "DC wiring (+ / −)",
        "eyebrow": "Solar DC home · pictorial concept",
        "h1": "A home that runs on <em>its own sunshine</em>",
        "lead": "A two-storey home: solar panels face south, the entrance faces east, and every light, fan, socket, the boundary lights and even the gate motor run on safe 48 V DC from the roof and battery.",
        "see": "What you <em>see</em>",
        "inside_h": "Inside: <em>everything runs on DC</em>",
        "enquiry": "Want your home or project to run on <em>solar DC?</em>",
        "whatsapp": "WhatsApp",
    },
    "hi": {
        "title": "सोलर डीसी घर",
        "south": "दक्षिण", "north": "उत्तर", "east_entrance": "पूर्व · प्रवेश द्वार",
        "N": "उ", "S": "द", "E": "पू", "W": "प",
        "sun": "दक्षिण आकाश में सूर्य",
        "panels_face": "पैनल दक्षिण की ओर, ताकि दिन भर धूप मिले",
        "north_balcony": "उत्तर बालकनी", "tank": "टंकी",
        "panels_tilted": "सोलर पैनल दक्षिण की ओर झुके हुए",
        "bedroom": "शयन कक्ष", "family_room": "पारिवारिक कक्ष", "staircase": "सीढ़ी",
        "living_room": "बैठक", "kitchen": "रसोई", "dc_utility": "डीसी यूटिलिटी कक्ष",
        "riser_1": "डीसी राइज़र", "riser_2": "नीचे के बोर्ड से",
        "charge_controller": "चार्ज कंट्रोलर", "battery": "बैटरी", "with_bms": "BMS सहित",
        "dc_board": "डीसी बोर्ड", "distribution": "48&#160;V वितरण",
        "boundary_gate": "बाउंड्री लाइट और गेट मोटर",
        "legend": [
            ("दक्षिण की ओर सोलर पैनल", "छत पर झुकी पंक्तियाँ सुबह से शाम तक धूप पकड़ती हैं।"),
            ("सीढ़ी कक्ष और पानी की टंकी", "छत उपयोग में रहती है; पैनल टंकी की छाया से दूर हैं।"),
            ("पूर्व की ओर प्रवेश", "दरवाज़े पर सुबह की रोशनी; डीसी लाइट और सीढ़ियों वाला पोर्च।"),
            ("बाउंड्री दीवार की लाइटें", "हर खंभे पर डीसी लैंप रात में आँगन रोशन करते हैं।"),
            ("स्लाइडिंग गेट", "बाउंड्री दीवार के अंदर की ओर रेल पर सरकता है।"),
            ("डीसी गेट मोटर", "बिजली कटौती में भी बैटरी से गेट खोलती और बंद करती है।"),
            ("पोर्च लाइट", "मुख्य दरवाज़े पर ड्राइवर-रहित डीसी एलईडी।"),
            ("डीसी केबल मार्ग", "लाल (+) और काली (−) केबल पैनलों से डीसी यूटिलिटी कक्ष तक जाती हैं।"),
            ("उत्तर बालकनी", "पहली मंज़िल पर उत्तर की ओर बालकनी, जो उत्तर-पूर्व कोने तक जाती है। उत्तर की नरम, चकाचौंध-रहित रोशनी और अपनी डीसी दीवार लाइट।"),
        ],
        "inside": ["छत पर सोलर", "MPPT चार्ज कंट्रोलर", "बैटरी + BMS", "48&#160;V डीसी बोर्ड", "ड्राइवर-रहित एलईडी लाइटें",
                   "BLDC पंखे और एग्ज़ॉस्ट", "टच पैनल", "मैकेनिकल स्विच", "डीसी और USB-C सॉकेट", "डीसी फ्रिज",
                   "गेट मोटर", "बाउंड्री लाइटें"],
        "wiring": "डीसी वायरिंग (+ / −)",
        "eyebrow": "सोलर डीसी घर · चित्र द्वारा समझें",
        "h1": "एक घर जो चलता है <em>अपनी ही धूप से</em>",
        "lead": "दो मंज़िला घर: सोलर पैनल दक्षिण की ओर, प्रवेश पूर्व की ओर। हर लाइट, पंखा, सॉकेट, बाउंड्री लाइटें और गेट मोटर भी छत और बैटरी से मिलने वाली सुरक्षित 48&#160;V डीसी बिजली पर चलते हैं।",
        "see": "आप क्या <em>देखते हैं</em>",
        "inside_h": "अंदर: <em>सब कुछ डीसी पर चलता है</em>",
        "enquiry": "क्या आप अपना घर या प्रोजेक्ट <em>सोलर डीसी</em> पर चलाना चाहते हैं?",
        "whatsapp": "व्हाट्सऐप",
    },
    "or": {
        "title": "ସୋଲାର ଡିସି ଘର",
        "south": "ଦକ୍ଷିଣ", "north": "ଉତ୍ତର", "east_entrance": "ପୂର୍ବ · ପ୍ରବେଶ ଦ୍ୱାର",
        "N": "ଉ", "S": "ଦ", "E": "ପୂ", "W": "ପ",
        "sun": "ଦକ୍ଷିଣ ଆକାଶରେ ସୂର୍ଯ୍ୟ",
        "panels_face": "ଦିନସାରା ଖରା ପାଇଁ ପ୍ୟାନେଲ ଦକ୍ଷିଣ ମୁହାଁ",
        "north_balcony": "ଉତ୍ତର ବାରଣ୍ଡା", "tank": "ଟାଙ୍କି",
        "panels_tilted": "ସୋଲାର ପ୍ୟାନେଲ ଦକ୍ଷିଣ ଆଡ଼କୁ ଢଳା",
        "bedroom": "ଶୋଇବା ଘର", "family_room": "ପରିବାର ଘର", "staircase": "ସିଡ଼ି",
        "living_room": "ବୈଠକ ଘର", "kitchen": "ରୋଷେଇ ଘର", "dc_utility": "ଡିସି ୟୁଟିଲିଟି ଘର",
        "riser_1": "ଡିସି ରାଇଜର", "riser_2": "ତଳ ବୋର୍ଡରୁ",
        "charge_controller": "ଚାର୍ଜ କଣ୍ଟ୍ରୋଲର", "battery": "ବ୍ୟାଟେରୀ", "with_bms": "BMS ସହିତ",
        "dc_board": "ଡିସି ବୋର୍ଡ", "distribution": "48&#160;V ବଣ୍ଟନ",
        "boundary_gate": "ବାଉଣ୍ଡାରି ଲାଇଟ ଓ ଗେଟ ମୋଟର",
        "legend": [
            ("ଦକ୍ଷିଣ ମୁହାଁ ସୋଲାର ପ୍ୟାନେଲ", "ଛାତ ଉପରେ ଢଳା ଧାଡ଼ି ସକାଳୁ ସନ୍ଧ୍ୟା ପର୍ଯ୍ୟନ୍ତ ଖରା ପାଏ।"),
            ("ସିଡ଼ି ଘର ଓ ପାଣି ଟାଙ୍କି", "ଛାତ ବ୍ୟବହାର ଯୋଗ୍ୟ ରହେ; ପ୍ୟାନେଲ ଟାଙ୍କିର ଛାଇରୁ ଦୂରରେ।"),
            ("ପୂର୍ବ ମୁହାଁ ପ୍ରବେଶ", "କବାଟରେ ସକାଳ ଆଲୋକ; ଡିସି ଲାଇଟ ଓ ପାହାଚ ସହ ପୋର୍ଟିକୋ।"),
            ("ବାଉଣ୍ଡାରି କାନ୍ଥ ଲାଇଟ", "ପ୍ରତି ଖୁଣ୍ଟରେ ଡିସି ଲ୍ୟାମ୍ପ ରାତିରେ ଅଗଣା ଆଲୋକିତ କରେ।"),
            ("ସ୍ଲାଇଡିଂ ଗେଟ", "ବାଉଣ୍ଡାରି କାନ୍ଥର ଭିତର ପଟେ ରେଳ ଉପରେ ଘୁଞ୍ଚେ।"),
            ("ଡିସି ଗେଟ ମୋଟର", "ବିଦ୍ୟୁତ କାଟ ସମୟରେ ମଧ୍ୟ ବ୍ୟାଟେରୀରେ ଗେଟ ଖୋଲେ ଓ ବନ୍ଦ କରେ।"),
            ("ପୋର୍ଟିକୋ ଲାଇଟ", "ମୁଖ୍ୟ କବାଟରେ ଡ୍ରାଇଭର-ବିହୀନ ଡିସି LED।"),
            ("ଡିସି କେବୁଲ ପଥ", "ଲାଲ (+) ଓ କଳା (−) କେବୁଲ ପ୍ୟାନେଲରୁ ଡିସି ୟୁଟିଲିଟି ଘର ପର୍ଯ୍ୟନ୍ତ ଯାଏ।"),
            ("ଉତ୍ତର ବାରଣ୍ଡା", "ପ୍ରଥମ ମହଲାରେ ଉତ୍ତର ପଟେ ବାରଣ୍ଡା, ଉତ୍ତର-ପୂର୍ବ କୋଣ ଘେରି। ଉତ୍ତରର ନରମ, ଝଲକ-ବିହୀନ ଆଲୋକ ଓ ନିଜର ଡିସି କାନ୍ଥ ଲାଇଟ।"),
        ],
        "inside": ["ଛାତ ଉପରେ ସୋଲାର", "MPPT ଚାର୍ଜ କଣ୍ଟ୍ରୋଲର", "ବ୍ୟାଟେରୀ + BMS", "48&#160;V ଡିସି ବୋର୍ଡ", "ଡ୍ରାଇଭର-ବିହୀନ LED ଲାଇଟ",
                   "BLDC ପଙ୍ଖା ଓ ଏକ୍ସହଷ୍ଟ", "ଟଚ୍ ପ୍ୟାନେଲ", "ମେକାନିକାଲ ସୁଇଚ", "ଡିସି ଓ USB-C ସକେଟ", "ଡିସି ଫ୍ରିଜ",
                   "ଗେଟ ମୋଟର", "ବାଉଣ୍ଡାରି ଲାଇଟ"],
        "wiring": "ଡିସି ୱାୟରିଂ (+ / −)",
        "eyebrow": "ସୋଲାର ଡିସି ଘର · ଚିତ୍ରରେ ବୁଝନ୍ତୁ",
        "h1": "ଏକ ଘର ଯାହା ଚାଲେ <em>ନିଜ ଖରାରେ</em>",
        "lead": "ଦୁଇ ମହଲା ଘର: ସୋଲାର ପ୍ୟାନେଲ ଦକ୍ଷିଣ ମୁହାଁ, ପ୍ରବେଶ ପୂର୍ବ ମୁହାଁ। ପ୍ରତିଟି ଲାଇଟ, ପଙ୍ଖା, ସକେଟ, ବାଉଣ୍ଡାରି ଲାଇଟ ଓ ଗେଟ ମୋଟର ମଧ୍ୟ ଛାତ ଓ ବ୍ୟାଟେରୀରୁ ମିଳୁଥିବା ସୁରକ୍ଷିତ 48&#160;V ଡିସିରେ ଚାଲେ।",
        "see": "ଆପଣ <em>କ'ଣ ଦେଖୁଛନ୍ତି</em>",
        "inside_h": "ଭିତରେ: <em>ସବୁକିଛି ଡିସିରେ ଚାଲେ</em>",
        "enquiry": "ଆପଣଙ୍କ ଘର ବା ପ୍ରୋଜେକ୍ଟ <em>ସୋଲାର ଡିସିରେ</em> ଚଳାଇବାକୁ ଚାହାନ୍ତି କି?",
        "whatsapp": "ହ୍ୱାଟସଆପ",
    },
}
